# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_hw',
                'doc_host': 'https://cgmonster3D.github.io',
                'git_url': 'https://github.com/cgmonster3D/nbdev_hw',
                'lib_path': 'nbdev_hw'},
  'syms': {'nbdev_hw.core': {'nbdev_hw.core.foo': ('core.html#foo', 'nbdev_hw/core.py')}}}
