# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/Stocks correlation.ipynb.

# %% auto 0
__all__ = ['say_hello', 'foo']

# %% ../nbs/Stocks correlation.ipynb 3
def say_hello(to):
    "Say hello to somebody"
    return f'Hello {to}!'

# %% ../nbs/Stocks correlation.ipynb 4
def foo(): pass
